'use strict';
(()=>{
 const data=window.SOTA_TACTILE;if(!data)return;
 // Values are already post-clip activations. Never apply the [0.1,2.0] rescale here.
 // Dividing by scaleMax only chooses a display color; it does not change the signal.
 const ns='http://www.w3.org/2000/svg',instances=new Map();
 const clipName=v=>v.querySelector('source')?.getAttribute('src').split('/').pop().replace('.mp4','')||v.getAttribute('src')?.split('/').pop().replace('.mp4','');
 function color(value){const i=Math.max(0,Math.min(255,Math.floor(value/data.scaleMax*256)));return `rgb(${data.palette[i].join(',')})`}
 function radius(value,index,nearest=data.nearest){return Math.min(nearest[index]*(.48+.48*Math.max(0,Math.min(1,value/.025))),14)}
 function mount(video){
  let name=clipName(video),clip=data.clips[name];if(!clip)return;
  const panel=document.createElement('div');panel.className='tactile-panel';panel.setAttribute('aria-label','Recorded tactile signals synchronized to video');
  panel.innerHTML=`<div class="tactile-map"><svg viewBox="73 47 622 674" role="img" aria-label="Recorded activation across 202 tactile sensing points"><image href="assets/tactile-hand.png" width="768" height="768"/><g class="taxels"></g></svg></div><div class="tactile-trace"><div class="signal-label">RECORDED TOUCH <output class="signal-time">0.00 s</output></div><svg viewBox="0 0 240 76" preserveAspectRatio="none" role="img" aria-label="Maximum recorded taxel activation over the episode, with a playback cursor"><line x1="1" x2="239" y1="65" y2="65" stroke="#b8c0b2"/><path class="signal-path" fill="none" stroke="#b84675" stroke-width="1.5"/><line class="signal-cursor" x1="0" x2="0" y1="4" y2="66" stroke="#294d36" stroke-width="1.5"/><circle class="signal-point" r="3" fill="#294d36"/></svg><div class="signal-scale"><span>0</span><span class="color-ramp" aria-hidden="true"></span><span>≥0.20</span><span>activation</span></div><div class="signal-note">202 taxels · peak activation trace</div></div>`;
  if(video.closest('.hero-media'))video.closest('.hero-media').after(panel);else if(video.closest('.video-shell'))video.closest('.video-shell').after(panel);else video.after(panel);
  const svg=panel.querySelector('.tactile-map svg'),group=panel.querySelector('.taxels');
  const circles=data.xy.map(([x,y])=>{const c=document.createElementNS(ns,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',radius(0,group.children.length));c.setAttribute('fill',color(0));group.append(c);return c});
  let peaks=[],last=-1;
  function load(){name=clipName(video);clip=data.clips[name];if(!clip)return;const human=clip.geometry==='human';svg.querySelector('image').setAttribute('href',human?'assets/tactile-human-hand.png':'assets/tactile-hand.png');circles.forEach((c,i)=>{const xy=(human?data.humanXY:data.xy)[i];c.setAttribute('cx',xy[0]);c.setAttribute('cy',xy[1])});svg.style.transform=clip.side==='left'?'scaleX(-1)':'';peaks=clip.values.map(a=>Math.max(...a));const path=peaks.map((v,i)=>`${i?'L':'M'}${(i/(peaks.length-1)*238+1).toFixed(2)},${(65-Math.min(v,data.scaleMax)/data.scaleMax*59).toFixed(2)}`).join(' ');panel.querySelector('.signal-path').setAttribute('d',path);last=-1;draw(0)}
  function draw(time){const frame=Math.max(0,Math.min(clip.values.length-1,Math.floor(time*clip.fps+1e-4)));if(frame===last)return;last=frame;circles.forEach((c,j)=>{c.setAttribute('fill',color(clip.values[frame][j]));c.setAttribute('r',radius(clip.values[frame][j],j,clip.geometry==='human'?data.humanNearest:data.nearest))});const x=frame/(clip.values.length-1)*238+1;panel.querySelector('.signal-cursor').setAttribute('x1',x);panel.querySelector('.signal-cursor').setAttribute('x2',x);panel.querySelector('.signal-point').setAttribute('cx',x);panel.querySelector('.signal-point').setAttribute('cy',65-Math.min(peaks[frame],data.scaleMax)/data.scaleMax*59);panel.querySelector('output').textContent=(frame/clip.fps).toFixed(2)+' s';panel.dataset.frame=String(frame);panel.dataset.clip=name}
  if(video.requestVideoFrameCallback){const tick=(now,meta)=>{draw(meta.mediaTime);video.requestVideoFrameCallback(tick)};video.requestVideoFrameCallback(tick)}
  video.addEventListener('timeupdate',()=>draw(video.currentTime));video.addEventListener('seeked',()=>draw(video.currentTime));video.addEventListener('loadedmetadata',()=>draw(video.currentTime));load();instances.set(video,{load,panel});
 }
 document.querySelectorAll('video').forEach(mount);
 const comparisons={"box-id":{"label":"Box \u00b7 ID \u00b7 Training box","clips":["box-id-baseline","box"],"outcomes":["success","success"],"condition":"The evaluation uses the box seen in robot training.","captions":["The recorded rollout completes the task.","The recorded rollout completes the task."]},"box-ood":{"label":"Box \u00b7 OOD-1 \u00b7 2.8\u00d7 heavier","clips":["box-baseline","box-ood"],"outcomes":["fail","success"],"condition":"The unseen evaluation box is 2.8\u00d7 heavier than the training box.","captions":["The recorded rollout does not complete the task.","The recorded rollout completes the task."]},"cup-id":{"label":"Cup \u00b7 ID \u00b7 Training cups","clips":["cup-id-baseline","cup"],"outcomes":["success","success"],"condition":"The evaluation uses the cups seen in robot training.","captions":["The recorded rollout completes the task.","The recorded rollout completes the task."]},"cup-square":{"label":"Cup \u00b7 OOD-1 \u00b7 Square base","clips":["cup-square-baseline","cup-square"],"outcomes":["success","success"],"condition":"The unseen evaluation cups have a square base, unlike the round-base training cups.","captions":["The recorded rollout completes the task.","The recorded rollout completes the task."]},"cup-tall":{"label":"Cup \u00b7 OOD-2 \u00b7 Stack 21 mm higher","clips":["cup-baseline","cup-cotrain"],"outcomes":["fail","success"],"condition":"The evaluation stack is 21 mm higher than the training stack.","captions":["The recorded rollout does not complete the task.","The recorded rollout completes the task."]},"plug-id":{"label":"Plug \u00b7 ID \u00b7 Training plug","clips":["plug-id-baseline","plug"],"outcomes":["success","success"],"condition":"The evaluation uses the plug seen in robot training.","captions":["The recorded rollout completes the task.","The recorded rollout completes the task."]},"plug-light":{"label":"Plug \u00b7 OOD-1 \u00b7 32 g heavier","clips":["plug-light-baseline","plug-ood1"],"outcomes":["fail","success"],"condition":"The unseen evaluation plug is 32 g heavier than the training plug.","captions":["The recorded rollout does not complete the task.","The recorded rollout completes the task."]},"plug-heavy":{"label":"Plug \u00b7 OOD-2 \u00b7 109 g heavier","clips":["plug-baseline","plug-ood2"],"outcomes":["fail","success"],"condition":"The unseen evaluation plug is 109 g heavier than the training plug.","captions":["The recorded rollout does not complete the task.","The recorded rollout completes the task."]}};
 document.querySelector('#comparison-task').addEventListener('change',event=>{const spec=comparisons[event.target.value];document.querySelectorAll('.comparison-video').forEach((video,i)=>{const name=spec.clips[i];video.pause();video.querySelector('source').setAttribute('src',`assets/${name}.mp4`);video.poster=`assets/${name}.webp`;video.setAttribute('aria-label',`${spec.label}: ${i?'co-training':'robot-only'} ${spec.outcomes[i]}`);const badge=video.closest('figure').querySelector('.outcome');badge.className='outcome '+spec.outcomes[i];badge.textContent=spec.outcomes[i]==='success'?'Success':'Failure';instances.get(video).load();video.load()});document.querySelector('#comparison-baseline-caption').textContent=spec.captions[0];document.querySelector('#comparison-full-caption').textContent=spec.captions[1];document.querySelector('#comparison-condition').textContent=spec.condition});
 document.querySelectorAll('[data-video-select]').forEach(select=>select.addEventListener('change',()=>{const card=select.closest('.demo-card'),video=card.querySelector('video'),name=select.value;video.pause();video.querySelector('source').setAttribute('src',`assets/${name}.mp4`);video.poster=`assets/${name}.webp`;video.setAttribute('aria-label',select.selectedOptions[0].textContent+' successful evaluation');instances.get(video).load();video.load();card.querySelector('.demo-meta span').textContent=(name===select.dataset.videoSelect?'ID':'OOD')+' · SUCCESS'}));
})();
